# Generated by Django 2.0 on 2020-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT_FIRST_NAME', models.CharField(default='NULL', max_length=250)),
                ('PATIENT_LAST_NAME', models.CharField(default='NULL', max_length=250)),
            ],
        ),
    ]
