# Generated by Django 2.0 on 2020-06-13 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='AADHAR_NO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='BLOOD_GRP',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='DOB',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='FATHER_NAME',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='GENDER',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='HEIGHT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='MAIL',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='MARITAL_STATUS',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='MOBILE_NO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='MOTHER_NAME',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='PASSWORD',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='PAYMENT_STATUS',
            field=models.CharField(default='NO', max_length=50),
        ),
        migrations.AddField(
            model_name='patients',
            name='WEIGHT',
            field=models.IntegerField(default=0),
        ),
    ]
