# Generated by Django 2.0 on 2020-06-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_auto_20200613_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(auto_now_add=True)),
                ('appointment_time', models.TimeField(auto_now=True)),
                ('doctor_name', models.CharField(max_length=230)),
                ('patient_appointment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.patients')),
            ],
        ),
    ]
