# Generated by Django 2.0 on 2020-06-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_patient_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patient_appointment',
            new_name='patient_appointment_details',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='APPONITMENT_STATUS',
            new_name='APPOINTMENT_STATUS',
        ),
    ]
