# Generated by Django 2.0 on 2020-06-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_auto_20200614_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
