# Generated by Django 2.0 on 2020-06-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_patients_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='CITY',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='POSTAL_CODE',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='STATE',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patients',
            name='STREET_ADDRESS',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
