# Generated by Django 2.0 on 2020-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_auto_20200614_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='APPOINTMENT_STATUS',
            new_name='APPOINTMENT_STATUS_RECEPTIONIST',
        ),
        migrations.AddField(
            model_name='patients',
            name='APPOINTMENT_STATUS_DOCTOR',
            field=models.CharField(default='NOT PROCEEDED', max_length=50),
        ),
    ]
