# Generated by Django 2.0 on 2020-06-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_auto_20200616_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='MOBILE_NO',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
