# Generated by Django 2.0 on 2020-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_auto_20200617_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_appointment_details',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='patient_appointment_details',
            name='preferred_location',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patient_appointment_details',
            name='problem',
            field=models.CharField(default='NULL', max_length=250),
        ),
        migrations.AddField(
            model_name='patient_appointment_details',
            name='speciality',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
