# Generated by Django 2.0 on 2020-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0013_auto_20200617_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment_details',
            name='doctor_name',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
