# Generated by Django 2.0 on 2020-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_patient_appointment_details_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment_details',
            name='reason_of_rejection',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
