# Generated by Django 2.0 on 2020-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_patient_appointment_details_reason_of_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
