# Generated by Django 2.0 on 2020-06-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_patients_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='count',
        ),
    ]
