# Generated by Django 2.0 on 2020-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0017_remove_patients_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment_details',
            name='doctor',
            field=models.IntegerField(default=0),
        ),
    ]
