# Generated by Django 2.0 on 2020-06-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0018_patient_appointment_details_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_appointment_details',
            old_name='doctor',
            new_name='doctor_id',
        ),
    ]
