# Generated by Django 2.0 on 2020-06-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_doctors_patient_count'),
        ('Patient', '0019_auto_20200619_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_appointment_details',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='patient_appointment_details',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctor.doctors'),
        ),
    ]
