# Generated by Django 2.0 on 2020-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0020_auto_20200621_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients_account_details',
            name='account_no',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
