# Generated by Django 2.0 on 2020-06-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0021_auto_20200622_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='prescription',
            field=models.CharField(default='NA', max_length=250),
        ),
    ]
