# Generated by Django 2.0 on 2020-06-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0022_medical_history_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_history',
            old_name='medical_id',
            new_name='medical',
        ),
    ]
