# Generated by Django 2.0 on 2020-06-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0024_auto_20200622_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_appointment_details',
            old_name='reason_of_rejection',
            new_name='notification',
        ),
    ]
