# Generated by Django 2.0 on 2020-06-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0025_auto_20200623_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='APPOINTMENT_STATUS_DOCTOR',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='APPOINTMENT_STATUS_RECEPTIONIST',
        ),
        migrations.AddField(
            model_name='patient_appointment_details',
            name='APPOINTMENT_STATUS_DOCTOR',
            field=models.CharField(default='NOT PROCEEDED', max_length=50),
        ),
        migrations.AddField(
            model_name='patient_appointment_details',
            name='APPOINTMENT_STATUS_RECEPTIONIST',
            field=models.CharField(default='NO', max_length=50),
        ),
    ]
