# Generated by Django 2.0 on 2020-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0026_auto_20200623_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='PAYMENT_STATUS',
        ),
        migrations.AddField(
            model_name='patient_appointment_details',
            name='PAYMENT_STATUS',
            field=models.CharField(default='NO', max_length=50),
        ),
    ]
