# Generated by Django 2.0 on 2020-06-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0027_auto_20200623_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_appointment_details',
            old_name='patient_appointment_id',
            new_name='patient_appointment',
        ),
    ]
