# Generated by Django 2.0 on 2020-06-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0029_patients_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_account_details',
            name='appointment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.patient_appointment_details'),
        ),
    ]
