# Generated by Django 2.0 on 2020-06-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0030_patients_account_details_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients_account_details',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
