# Generated by Django 2.0 on 2020-06-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOCTOR_FIRST_NAME', models.CharField(default='NULL', max_length=250)),
                ('DOCTOR_LAST_NAME', models.CharField(default='NULL', max_length=250)),
                ('PASSWORD', models.CharField(default='NULL', max_length=250)),
                ('MAIL', models.CharField(default='NULL', max_length=250)),
                ('FATHER_NAME', models.CharField(default='NULL', max_length=250)),
                ('MOTHER_NAME', models.CharField(default='NULL', max_length=250)),
                ('GENDER', models.CharField(default='NULL', max_length=250)),
                ('BLOOD_GRP', models.CharField(default='NULL', max_length=250)),
                ('DOB', models.DateField(auto_now_add=True)),
                ('STREET_ADDRESS', models.CharField(default='NULL', max_length=250)),
                ('CITY', models.CharField(default='NULL', max_length=250)),
                ('STATE', models.CharField(default='NULL', max_length=250)),
                ('POSTAL_CODE', models.CharField(default='NULL', max_length=250)),
                ('MARITAL_STATUS', models.CharField(default='NULL', max_length=250)),
                ('MOBILE_NO', models.CharField(default='NULL', max_length=20, unique=True)),
                ('AADHAR_NO', models.CharField(default='NOT AVAILABLE', max_length=34, unique=True)),
                ('QUALIFICATION', models.CharField(default='NOT AVAILABLE', max_length=34, unique=True)),
                ('PATIENT_IMG', models.ImageField(blank=True, upload_to='patient_img')),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
