# Generated by Django 2.0 on 2020-06-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='PATIENT_IMG',
        ),
        migrations.AddField(
            model_name='doctors',
            name='DOCTOR_IMG',
            field=models.ImageField(blank=True, upload_to='doctor_img'),
        ),
    ]
