# Generated by Django 2.0 on 2020-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20200616_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='BLOOD_GRP',
        ),
        migrations.AddField(
            model_name='doctors',
            name='SPECIALISATION',
            field=models.CharField(default='NOT AVAILABLE', max_length=34, unique=True),
        ),
    ]
