# Generated by Django 2.0 on 2020-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_auto_20200616_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='PATIENT_COUNT',
            field=models.IntegerField(default=0),
        ),
    ]
