# Generated by Django 2.0 on 2020-06-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_doctors_patient_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='PATIENT_COUNT',
        ),
    ]
