# Generated by Django 2.0 on 2020-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_remove_doctors_patient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='Country',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
