# Generated by Django 2.0 on 2020-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_doctors_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='QUALIFICATION',
            field=models.CharField(default='NOT AVAILABLE', max_length=34),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='SPECIALISATION',
            field=models.CharField(default='NOT AVAILABLE', max_length=34),
        ),
    ]
