# Generated by Django 2.0 on 2020-06-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receptionists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptionist_first_name', models.CharField(max_length=200)),
                ('receptionist_last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
    ]
